spring:
  datasource:
    url: jdbc:mysql://localhost:3306/source
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
      username: root
      password: 1234
      uri: mongodb://root:1234@localhost:27017

server:
  port: 7999