spring:
  datasource:
    url: jdbc:mysql://localhost:3307/target
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

server:
  port: 7999